server:
  port: 8007
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/kyb-ai?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: ai-service
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${BL_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: qwen-max
          temperature: 0.9
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 4
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug